config/routes.rb
Rails.application.routes.draw do
  get 'steps/new'

  resources :orders do
    member do
      get 'pay'
      get 'charge'
    end
  end
  resources :line_items
  resources :carts do
    collection do
      delete :destroy_all
    end
  end
  root 'saliva_pages#home'
  get 'about' => 'saliva_pages#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get 'favorite'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :dishes do
    collection do
      get :search
    end
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/order.rb
require 'pingpp'
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  belongs_to :user
  PAYMENT_TYPES = ["北京市"]
  PAYMENT_TYPES2 = ["海淀区","朝阳区"]

  #validates :address, inclusion: PAYMENT_TYPES
  #validates :address2, inclusion: PAYMENT_TYPES2
  #validates :name, :address3, presence: true
  #validates :phone, presence: true

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
  
  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end

  def pay_url
    #获取api_key以及app_id
    Pingpp.api_key = "sk_test_iLCK0O4qLaLK5e5O4C4mnLiP"
    app_id = "app_0iLejH0y5SaLHK4C"
    #不同支付渠道的回调地址
    #ping++平台新建一个订单
    begin
      charge = Pingpp::Charge.create(
        order_no: order_no,
        app: {id: app_id},
        channel: "alipay_pc_direct",
        amount: 10,
        client_ip: "10.129.204.83",
        currency: "cny",
        subject: "saliva purchase",
        body: "My body",
        extra: {success_url: "http://www.salivagroup.cn/orders/#{id}"}
      )

      return charge
    rescue Pingpp::PingppError => error
      logger.error 'ping++平台创建订单失败'
      logger.error error.http_body
      return false
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :pay, :charge]
  before_action :logged_in_user, only: [:destroy, :index]
  before_action :admin_user, only: [:destroy, :index]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.paginate page: params[:page],  per_page: 10

    respond_to do |format|
      format.html
      format.json {render json: @orders}
    end
  end

  # GET /orders/1
  # GET /orders/1.json 此处并未使用show动作，直接跳转到pay
  def show
  end

  def pay
    order_no = (Time.now.to_formatted_s(:number)).to_s
    6.times {order_no << rand(10).to_s}
    @order.order_no = order_no
    @@charge = @order.pay_url
    if @@charge == false
    else
      @order.update_attribute(:charge_no, (JSON.parse @@charge.to_s)['id'])
    end
  end

  def charge
    render json: @@charge
  end

  # GET /orders/new
  def new
    @cart = current_cart
    if @cart.line_items.empty?
      redirect_to root_url, notice: "你的购物车是空的"
      return
    end
    #@order = Order.new
    ############没有调用create动作，直接调用pay#################
    if logged_in?    
      @order = current_user.orders.build
    else
      @order = Order.new
    end
    @order.add_line_items_from_cart(current_cart)
    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        format.html { redirect_to pay_order_path(@order) }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
    ################################
    #respond_to do |format|
    #  format.html
    #  format.json {render json: @order}
    #end
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    #@order = Order.new(order_params)
    if logged_in?    
      @order = current_user.orders.build(order_params)
    else
      @order = Order.new(order_params)
    end
    @order.add_line_items_from_cart(current_cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        format.html { redirect_to pay_order_path(@order) }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :address2, :address3, :phone)
    end

    def correct_user
      @order = current_user.orders.find_by(id: params[:id])
      redirect_to root_url if @order.nil?
    end

    def admin_user
      redirect_to root_url unless current_user.admin
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2">
      </div>
      <div class="col-md-8">
        <div class="field">
          <%= f.label :姓名 %><br>
          <%= f.text_field :name, size: 40, class: 'form-control form-field' %>
        </div>
        <div class="field">
          <%= f.label :地址 %><br>
          <%= f.select :address, Order::PAYMENT_TYPES, {prompt: '选择城市'}, {class: 'form-control form-field'} %>
          <%= f.select :address2, Order::PAYMENT_TYPES2, {prompt: '选择区域'}, {class: 'form-control form-field'} %>
          <%= f.text_area :address3, class: 'form-control form-field', placeholder: '详细地址...' %>
        </div>
        <div class="field">
          <%= f.label :手机号码 %><br>
          <%= f.text_field :phone, size: 20, class: 'form-control form-field' %>
        </div>
        <div class="actions">
          <%= f.submit '付款', class: "OKBtn btn btn-primary" %>
        </div>
      </div>
      <div class="col-md-2">
      </div>
    </div>
  </div>
<% end %>

app/views/orders/_order.html.erb
<%= render order.line_items %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>订单列表</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.address2 %></td>
        <td><%= order.address3 %></td>
        <td><%= order.phone %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>
<p><%= will_paginate @orders %></p>

app/views/orders/new.html.erb
<div class="container-fluid order_new">
  <div class="row">
    <div class="col-md-6 saliva_form">
      <fieldset>
        <legend>请输入你的信息</legend>
        <%= render 'form' %>
      </fieldset>
    </div>

    <div class="col-md-6 saliva_order">
      <div class="container-fluid order_table">
        <div class="row">
          <div class="col-md-12">
            <%= image_tag "reco.png" %>
            <span class="reco">订单详情</span>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <table>
              <%= render @cart.line_items %>
              <tr class="total_line">
                <td colspan="2" style="color: rgb(77,31,10); font-weight: bold;">总价</td>
                <td class="total_cell"><%= number_to_currency @cart.total_price %></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/pay.html.erb
<!--
<script src="../../assets/javascripts/require.js"></script>
<script src="../../assets/javascripts/pingpp.js"></script>
-->
<script>
var charge = null; 
$.getJSON('<%= charge_order_path(@order) %>', function(data){
    charge = data;
    pingpp.createPayment(charge, function(result, err){
      
    });
    
});
    console.log("hohoho");
console.log("<%= @order.order_no %>");
</script>

app/views/orders/show.html.erb
<div class="order-show">
<p id="notice"><%= notice %></p>

<% if false %>
  <%= link_to 'Edit', edit_order_path(@order) %> |
  <%= link_to 'Back', orders_path %>
  <%= link_to 'Pay', pay_order_path(@order) %>
<% end %>

    <div class="order_info">
      <div class="container-fluid order_table order_table2">
        <div class="row">
          <div class="col-md-12">
            <%= image_tag "reco.png" %>
            <span class="reco">感谢您对作者的尊重^_^</span>
          </div>
        </div>
        <div>
            <table>
              <%= render @order %>
              <tr class="total_line">
                <td colspan="2" style="color: rgb(77,31,10); font-weight: bold;">打赏:</td>
                <td class="order_cell">￥<%= @order.total_price %></td>
              </tr>
            </table>
            <% if false %>
            <table>
              <tr class="order_line">
                <td colspan="2" style="color: #f9b597; font-weight: bold;">姓名</td>
                <td class="order_cell"><%= @order.name %></td>
              </tr>
              <tr class="order_line">
                <td colspan="2" style="color: #f9b597; font-weight: bold;">地址</td>
                <td class="order_cell"><%= @order.address %><%= @order.address2 %><%= @order.address3 %></td>
              </tr>
              <tr class="order_line">
                <td colspan="2" style="color: #f9b597; font-weight: bold;">电话</td>
                <td class="order_cell"><%= @order.phone %></td>
              </tr>
            </table>
            <% end %>
        </div>
      </div>
    </div>
</div>