config/routes.rb
Rails.application.routes.draw do
  get 'steps/new'

  resources :orders do
    member do
      get 'pay'
      get 'charge'
    end
  end
  resources :line_items
  resources :carts do
    collection do
      delete :destroy_all
    end
  end
  root 'saliva_pages#home'
  get 'about' => 'saliva_pages#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get 'favorite'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :dishes do
    collection do
      get :search
    end
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_dish(dish_id)
    current_item = line_items.find_by_dish_id(dish_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(dish_id: dish_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      set_cart
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_url, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html
        format.json {render json: @cart}
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_all
    @carts = Cart.all
    @carts.destroy_all
    redirect_to carts_path
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to carts_path }
      format.js
      format.json { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="glyphicon glyphicon-shopping-cart"></div>
<table>
  <tr class="total_title">
    <td>菜品</td>
    <td>数量</td>
    <td>价格</td>
  </tr>
  <%= render cart.line_items %>
  <tr class="total_line">
    <td colspan="2">总价</td>
    <td class="total_cell"><%= number_to_currency @cart.total_price %></td>
  </tr>
</table>
<div class="cart_btn">
<%= button_to '提交订单', new_order_path, method: :get, class: "orderbtn OKBtn btn btn-primary"%>
<%= button_to '清空购物车', @cart, method: :delete, class: "OKBtn btn btn-primary", remote: true %>
</div>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
$("#cart").html("<%= escape_javascript(render @cart) %>")
$('#notice').hide()

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Destroy_all', destroy_all_carts_path, method: :delete, data: { confirm: 'Are you sure?' } %>
<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="cart_title">我的购物车</div>
<table>
  <%= render @cart %>
  <tr class="total_line">
    <td colspan="2">总价</td>
    <td class="total_cell"><%= number_to_currency @cart.total_price %></td>
  </tr>
</table>

<%= button_to '清空购物车', @cart, method: :delete, confirm: '确定吗？', class: "OKBtn" %>