config/routes.rb
Rails.application.routes.draw do
  get 'steps/new'

  resources :orders do
    member do
      get 'pay'
      get 'charge'
    end
  end
  resources :line_items
  resources :carts do
    collection do
      delete :destroy_all
    end
  end
  root 'saliva_pages#home'
  get 'about' => 'saliva_pages#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get 'favorite'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :dishes do
    collection do
      get :search
    end
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Saliva</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <% unless current_page?(login_path) or current_page?(signup_path) %>
    <nav class="navbar navbar-inverse navbar-fixed-top mynav">
	    <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			      <span class="sr-only">Toggle navigation</span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
		      </button>
          <%= image_tag "logo.png" %>
		    </div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
            <li><%= link_to "首页", root_path, class: "nav-text" %></li> <!--美食菜单，只是线上，可配送-->
            <li><%= link_to "菜品", dishes_path, method: :get, class: "nav-text" %></li> <!--美食菜单，只是线上，可配送-->
            <li><%= link_to "关于我们", about_path, class: "nav-text" %></li> <!--没什么可介绍的-->
          </ul>
      <!--导航栏中增加搜索-->
          <div class="navbar-form navbar-left">    
            <%= form_tag search_dishes_path, :method => :get do %>
			      <div class="input-group">   
              <%= text_field_tag :query, params[:query], class:"form-control", placeholder:"发现食物……" %>
	            <span class="input-group-btn">
                <%= button_tag "", type: 'submit', class: "btn glyphicon glyphicon-search" do %><% end %>
	            </span>
	          </div>
            <% end %>
          </div>

		      <ul class="nav navbar-nav navbar-right" style="margin-right:30px;">
          <% if logged_in? %>
            <li><%= link_to "#{@current_user.name}", current_user %></li>
            <li><%= link_to "创建菜谱", new_dish_path %></li>
            <% if @current_user.admin %>
              <li><%= link_to "所有用户", users_path %></li>
              <li><%= link_to "所有订单", orders_path %></li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">账户<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "我的最爱", favorite_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "资料", current_user %></li>
                <li><%= link_to "设置", edit_user_path(current_user), target: "_blank" %></li>
                <li class="divider"></li>
                <li><%= link_to "退出", logout_path, method: "delete" %></li>
              </ul>
            </li>    
          <% else %>
            <li><%= link_to "登录", login_path, target: "_blank" %></li>
            <li><%= link_to "注册", signup_path, target: "_blank" %></li>
          <% end %>
		      </ul>
		    </div><!-- /.navbar-collapse -->
	    </div><!-- /.container-fluid -->
	  </nav>
  <% end %>	


  <%= yield %>



  <% unless current_page?(signup_path) or current_page?(login_path) %>
    <div class="footer">
	    <div class="container-fluid">
	      <p>© Saliva Group 2016. All Rights Reserved.</p>
      </div>
    </div>
  <% end %>
</body>
<script>
$(document).ready(function(){
  var myFunction = function(){
    var empty = false;
    $('.form-field').each(function(){
      if($(this).val().length === 0){empty = true;}
    });
    if(empty)
      $('.FBBtn').attr('disabled', true);
    else
      $('.FBBtn').attr('disabled', false); 
  };
  $('.FBBtn').attr('disabled', true);
  $('.form-field').keyup(myFunction).mouseup(myFunction);
});
</script>
</html>